### ISSUE TITLE
Connecting Wiimote to Unity

### ISSUE THREAD

**Issue by Jroosterman** [Flafla2/Unity-Wiimote#11]
I am trying to use your repo to get wiimote to interact with my game.  I am currently using GlovePie to connect the Wii mote after which, I am able to connect a Wii mote and use it in my game.  However, since our audience is for the blind, all of these steps are too convoluted.  I was wondering if there is an easier way to connect a Wii mote to a PC and use it with your repo.

**Comment by carlotes247** [comment]
I was using the instructions listed on the dolphin emulator website for pairing a Wiimote (http://www.dolphin-emulator.com/connect-wiimote.html). Is quite simple, but the problem using this method is that when the wiimote runs out of battery, you need to change it and pair it again with the computer. Does anybody know a better solution for the pairing?

**Comment by Jroosterman** [comment]
I was working off of this article (http://gamedev.stackexchange.com/questions/100468/interfacing-wiimote-with-unity-5)  Where they use glovePie to connect the wii mote to the pc which allows you to use it with unity.  However, it is not a very simple solution and GlovePie is not a very official looking program.

**Comment by Flafla2** [comment]
My project assumes that the Wiimote is properly connected through your Operating System's HID interface.  You could attempt to roll with a completely custom bluetooth driver that autoconnects to Wii Remotes but that is beyond the scope of this project.

To add to this, from what I understand the syncing process that is possible on the Wii (where you only have to sync the remote once and can use the 1+2 buttons to connect after the wiimote is paired with the console) can only be implemented at a driver level.

You can also check out the [Mayflash DophinBar](https://dolphin-emu.org/blog/2014/08/23/dolphinbar-review/) which has a built-in driver written specifically for the wiimote.

**Comment by davidfcalle** [comment]
I managed to connect a wiimote using this driver http://julianloehr.de/educational-work/hid-wiimote/ but, it doesn't recognize the wiimote

**Comment by jloehr** [comment]
The current problem with my driver is, that it does not support a "pass-through" mode yet. So it is currently blocking direct interaction with the Wiimote through the HID API.

**Comment by Flafla2** [comment]
I'm closing this issue for bookkeeping / organizational purposes.  If you have any further inquiries or questions feel free to ask me to reopen this issue or create a new one.
