### ISSUE TITLE
Unity crashes in the editor after running twice.

### ISSUE THREAD

**Issue by ptran099** [Flafla2/Unity-Wiimote#25]
If I run the game and then stop it, and then press play again then Unity crashes, every time. In my experience with Unity, this happened to me when I made native plugins in C++ with infinite loops in threads. Idk if this is helpful or anything. I just wanted to note it

**Comment by Flafla2** [comment]
Make sure to hit Cleanup() in the demo scene before quitting.  In a real game you should do this in OnDisable(), but for a technical demo I didn't worry about it.

**Comment by Flafla2** [comment]
Fixed with #27
