### ISSUE TITLE
IR how it work?

### ISSUE THREAD

**Issue by morghty** [Flafla2/Unity-Wiimote#29]
I try to move a 3D object with the wiiremote and the sensor bar but i don't understand how to get the IRData and get the the IR position to move my object. Can you help me plz?

**Comment by morghty** [comment]
i'm a new programmer and i'm studying in cegep for that but i have a project where i need to use this wiiremote, so I'm sorry for this stupid question

**Comment by Flafla2** [comment]
Sorry for the delay.  Please consult the documenation [included with major releases](https://github.com/Flafla2/Unity-Wiimote/releases) for detailed explanations on how to use features.
