### ISSUE TITLE
Question: How to pair wiimote with Mac OS?

### ISSUE THREAD

**Issue by thorikawa** [Flafla2/Unity-Wiimote#3]
I think this library requires that wiimote has to be paired with PC beforehand. If it's true, how to do that on Mac OS X?

**Comment by Flafla2** [comment]
The following instructions are reproducible on OS X El Capitan and Yosemite (at least):
1. Go to system preferences -> bluetooth
2. Press the red SYNC button on the back of the Wiimote or Wii U Pro Controller (on the wiimote this is under the battery cover)
3. Wait for "RVL-CNT-01" or similar to show up in the bluetooth system preferences pane
4. Click on "Pair" next to "RVL-CNT-01"

Also be sure to run WiimoteApi::WiimoteManager::Cleanup() before exiting your game.  On OS X, neglecting to run Cleanup() will force the user to reconnect the remote.

**Comment by thorikawa** [comment]
It works! Thank you very much.

**Comment by andreierdoss** [comment]
I think this information would be great if put in the README section.

**Comment by ghost** [comment]
It brings up a > entry thing.

**Comment by styczyn** [comment]
thank you, It works!

**Comment by Spikeyhair9** [comment]
@Flafla2 When I do this, it asks for a PIN. For the life of me I can't figure out what the PIN is. Any ideas?

**Comment by codfish172** [comment]
> @Flafla2 When I do this, it asks for a PIN. For the life of me I can't figure out what the PIN is. Any ideas?

I have the same issue it is also asking for a pin

**Comment by Spikeyhair9** [comment]
Those that have an M1 chip, you'll need to get a dolphin sensor. It takes button input and acts as the sensor.
