### ISSUE TITLE
Can't get the correct rotation

### ISSUE THREAD

**Issue by demonixis** [Flafla2/Unity-Wiimote#30]
Hi,

I try to use your library in a VR project and it's promising. I use two Wiimote for each hand. I can get the position of each wiimote but I can't get the rotation. How do you get the rotation?

Thanks.

**Comment by ghost** [comment]
How do you get the position? Please provide some code.
And you get the rotation only with a motionplus extension on your wiimote. Or you can calculate the gravity out of the raw acceleration data but that is very too inacurate and would be too complex.

**Comment by demonixis** [comment]
It's fixed thanks.
