### ISSUE TITLE
Missing features?

### ISSUE THREAD

**Issue by Grauen** [Flafla2/Unity-Wiimote#36]
Hi guys,

in the README i found this part:

> The API is capable of communicating and interpreting almost all useful data from the Wii Remote

Since the API can interpret almost all data, there is data which is not interpreted yet.
Can you list what is missing and why it is missing?

Sincerly
Grauen

**Comment by Flafla2** [comment]
Sorry for the delay, didn't see this with classes etc to worry about.

Right now we don't support sending sounds to the speaker, and we don't support a number of extension controllers (classic controller pro, nunchuck passthrough mode on the WMP are two big ones).
