### ISSUE TITLE
Getting buttons as Input

### ISSUE THREAD

**Issue by nicolasdulio** [Flafla2/Unity-Wiimote#37]
How do i get the info form the buttons as an input? 
I'd like to do something like this:

    if(Input.GetButtonDown("Button A"){
      ...
    }

**Comment by nicolasdulio** [comment]
Solved!
I don't know if this is the cleaner way to do it but it works:
    bool a = wiimote.Button.a;
    if (a)
    {
      ...
    }

**Comment by cascross123** [comment]
Hey, I'm trying to do the same thing but I can't work out how to get button input?
any help would be greatly appreciated

**Comment by nicolasdulio** [comment]
Of course, man! I were able to get the button input inside the WiimoteDemo.cs file. Here’s a basic example:

//capturing button input
        bool a = wiimote.Button.a;
        bool b = wiimote.Button.b;
        if (a)
        {
            Debug.Log(“Button A pressed");
        }
        if (b)
        {
            Debug.Log(“Button B pressed");
        }

Hope it helps.

Bye!

El 15 feb 2017, a las 0:34, Nick Jennett <notifications@github.com<mailto:notifications@github.com>> escribió:


Hey, I'm trying to do the same thing but I can't work out how to get button input?
any help would be greatly appreciated

**Comment by cascross123** [comment]
Thats great, thank you. Have you done anything with getting the accelerometer?

**Comment by odivalq** [comment]
Question: Can't you skip the middle man and just write your conditionals like the example below?

```
if (wiimote.Button.a)
{
Debug.Log(“Button A pressed");
}
```

**Comment by Flafla2** [comment]
@odivalq Yes, this is possible.

By the way everyone, I have included [comprehensive documentation in the formal release](https://github.com/Flafla2/Unity-Wiimote/releases).  Try that out instead of downloading the repo directly!
